---
apiVersion: wego.weave.works/v1alpha1
kind: Application
metadata:
  labels:
    wego.weave.works/app-identifier: wego-20ae51c1b7e359727d6696a0e6a3a576
  name: podinfo
  namespace: wego-system
spec:
  branch: main
  config_url: ssh://git@github.com/fire-ant/gitops-scratch.git
  deployment_type: kustomize
  path: ./
  source_type: git
  url: ssh://git@github.com/fire-ant/podinfo-deploy.git
